// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLopTBvEbN87zCNeVLj1D_licVG4rUHXk',
    appId: '1:231227130764:web:b871f38f044343baf60ca9',
    messagingSenderId: '231227130764',
    projectId: 'firebasics-c21e2',
    authDomain: 'firebasics-c21e2.firebaseapp.com',
    storageBucket: 'firebasics-c21e2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMWUb2T4FZDN6b56jD0bPSde_dmJ50bnA',
    appId: '1:231227130764:android:7d8adc54c4ffe6fef60ca9',
    messagingSenderId: '231227130764',
    projectId: 'firebasics-c21e2',
    storageBucket: 'firebasics-c21e2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgnB-oh7OyOVC3_KE71V9U0KiUyvigNGU',
    appId: '1:231227130764:ios:a8441f06b1310003f60ca9',
    messagingSenderId: '231227130764',
    projectId: 'firebasics-c21e2',
    storageBucket: 'firebasics-c21e2.firebasestorage.app',
    iosClientId: '231227130764-5djrq93l2tqrpfm3d65cso3sg7nbmk26.apps.googleusercontent.com',
    iosBundleId: 'com.example.nexus',
  );
}
